### ISSUE TITLE
The webhooks sink appears to be very light on testing

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#223]
There are few if any actual tests of any kind on the webhooks extension sink code.  Write some tests.

**Comment by a-roberts** [comment]
👍 

I think the following would be useful to get started:
- Can we trigger a PipelineRun for a given set of Pipelines based on a push event
- Can we trigger a PipelineRun for a given set of Pipelines based on pull request events
^^ includes checking we generate a PipelineResource of type git and image pointing to the correct repository and image location
- Get dashboard URL doesn't have a test (to be fair as Duane says there are no sink tests at all really)! There are some tests for interacting with hooks in webhook.go however
- Tests around the monitor task? May be a little tricky (how good is the fake Git client or would we want a functional ID with a token stored somewhere so we can properly test the sink/webhook/status table information for example)

**Comment by ncskier** [comment]
Although I think we really need more tests for the webhooks-extension, I don't think it would be worth adding tests to the sink right now, since issue https://github.com/tektoncd/experimental/issues/243 is in progress to remove the sink entirely (if I understand correctly). @mnuttall, @dibbles should we close this issue due to #243?

**Comment by dibbles** [comment]
Closing in favour of opening new test issue for triggers impl.
