### ISSUE TITLE
Webhook not deleted in Github when deleted in Tekton

### ISSUE THREAD

**Issue by csskinner25** [tektoncd/experimental#255]
# Expected Behavior

The webhook should be deleted in Github when it is deleted in Tekton.

This is the tekton version in the ICPA release. 

# Actual Behavior
Webhook is setup between tekton and github. The webhook is then deleted using the tekton dashboard. The webhook is not cleaned up in github. You have to manually delete the webhook in github. 
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by dibbles** [comment]
This is a problem that stems from knative - someone closed the issue I opened and never provided details about why/how they addressed the issue see (https://github.com/knative/eventing-contrib/issues/216#issuecomment-523473197)

I'm going to close this issue for now as it is being addressed by the move to an underlying triggers implementation and should no longer occur once issue 247 (https://github.com/tektoncd/experimental/issues/247) is completed.

I will quickly throw in a piece of documentation on the Limitations page so that people are aware of the current problem.
