### ISSUE TITLE
Use a go library/3rd party open source code to create webhook

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#327]
Currently the webhook is created using a Task - this is time consuming and difficult to monitor.  Change to using a go library to create the webhook in github and take cleanup actions if a failure occurs.

For example, if the webhook has been added to the eventlistener and then creation of the webhook fails, we should also remove the entry from the event listener.

Remove the Task yaml from the config directory and all the yaml files in which it is embedded.  Test code can also be removed from shared-test-funcs that creates/returns dummy reaults for taskruns.

**Comment by ncskier** [comment]
@dibbles does this work item also include deleting webhooks using the go library instead of the TaskRun, or is that going to be done under a separate PR?

**Comment by dibbles** [comment]
@ncskier yes create and delete - I should have been more or less specific in the details :)

**Comment by ncskier** [comment]
Since we aren't keeping track of the hook ID, I can't use the normal go-github hooks API to delete the webhook. go-github currently does not have PubSubHubbub supported (https://github.com/google/go-github/issues/1265), which is what our TaskRun is using to create & delete the webhook. So, for now I'm implementing this with a normal http request without using the go-github library directly for subscribing/unsubscribing to the PubSubHubbub API.

Note: I could not find a PubSubHubbub API for GitLab, so when we add support for GitLab, we might want to consider using the normal GitHub Hook API and storing the hook ID somewhere (https://docs.gitlab.com/ee/api/projects.html#hooks).

**Comment by dibbles** [comment]
Can you not simply  ......

1) get the webhooks
2) iterate over the webhooks checking for the matching callback url
3) delete the id of the webhook that matches

Agree with moving away from the pubsubhubbub - this was used as a workaround to an issue.

**Comment by ncskier** [comment]
Yeah... I wasn't thinking 😅 I saw that we were using the PubSubHubbub API in our TaskRun, so I thought that was a good reason to use it in the go code.

I created a new issue to switch from PubSubHubbub to the Hooks API: https://github.com/tektoncd/experimental/issues/362
