### ISSUE TITLE
Reduce RBAC ClusterRole / ClusterRoleBInding to not be cluster wide.

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#331]
Investigate (and implement) if we can reduce RBAC from ClusterRoleBinding/ClusterRole to RoleBinding and Role.

Would suggest testing multi-namespace webhooks, as triggers code runs from the install namespace but needs to be able to create artefacts in alternate namespaces.

**Comment by mnuttall** [comment]
I first checked Dashboard. This has one ClusterRole which appears in five places:
- config/dev-tekton-dashboard.yaml
- config/openshift/openshift-tekton-dashboard.yaml
- config/release/gcr-tekton-dashboard.yaml
- config/templates/deploy.yaml
- DEVELOPMENT.md

It's essentially the same content in each place. Since the dashboard is expected by default to cover all namespaces, this is fine: it's right to use a ClusterRole.
