### ISSUE TITLE
Access Token Management

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#38]
The 'first pass' at panelling for webhook management allows for access tokens to be created and deleted. We need a separate 'access token management' page where existing tokens can be presented in tabular form, as well as created and deleted. (Edit is not required.)

Consider whether users creating webhooks can be linked to and from a unified access token management dialog when creating one in the process of creating a webhook.

**Comment by kimholmes** [comment]
Is this a duplicate of #53 ?

**Comment by mi-wang** [comment]
What I have so far: (first pass)
![Secrets](https://user-images.githubusercontent.com/51759906/61238667-1d537b80-a70b-11e9-9274-a5522c81bc1d.png)

In process of finding a way to link webhooks and secrets

**Comment by mi-wang** [comment]
right hand side multi-select seems to be more intuitive
![right hand side multiselect](https://user-images.githubusercontent.com/51759906/61239282-8b4c7280-a70c-11e9-9ab4-ef22ed7af8ac.png)

**Comment by mi-wang** [comment]
My mistake! I thought Secrets were Access Tokens..

Here is a quick update on Access Token:
![1Access Token](https://user-images.githubusercontent.com/51759906/61379604-d9c95080-a875-11e9-8061-18dea7e76f58.png)
![2Access Token Import](https://user-images.githubusercontent.com/51759906/61379605-d9c95080-a875-11e9-98b8-0772e455043f.png)
![success](https://user-images.githubusercontent.com/51759906/61380404-4e50bf00-a877-11e9-96a3-84317ae6672d.png)

Invision link: https://ibm.invisionapp.com/share/9QNZ3R7SC4F

**Comment by ncskier** [comment]
It was discussed offline that since Access Tokens are used by Tekton [Pull Request Resources](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource), we can integrate Access Tokens into the core Dashboard's Secrets page, instead of making Access Tokens a separate Extensions page. 👍 

This raises a few design questions about how to create paneling for Secret with different types on one page. A big question I have is about _which_ Secrets we will display. Right now we filter to only show Secrets of type `corev1.SecretTypeBasicAuth` (code [here](https://github.com/tektoncd/dashboard/blob/master/pkg/endpoints/credential.go#L56)), but Access Tokens don't necessarily have a specific type. So how should we filter the Secrets page to only show BasicAuth and AccessToken Secrets? Would it be ok/better to show all types of secrets?

Also, would this be a good time to think about introducing SSHAuth Secrets to the Dashboard? (They're [supported by Tekton's authentication](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#authentication)). So maybe we should include them in the mockups even if the implementation work isn't given a high priority at the moment. (@mnuttall do you have any input on this?)

**Comment by mi-wang** [comment]
Latest Update:
Invision Link:
https://ibm.invisionapp.com/share/UBNZ3TAXAY2

**Comment by mii-w** [comment]
Updated Invision link:
https://ibm.invisionapp.com/share/X8NZ5IMQM4B

Please let me know if any links are broken and if you have any feedback/comment would be greatly appreciated :)

**Comment by kimholmes** [comment]
Comments on Invision prototype:
For the first screen you come to, it would better to start at the top of the detail window, and then show the screen where it has scrolled down:
![temp1](https://user-images.githubusercontent.com/21316329/62487314-7d2fc600-b78f-11e9-8fa2-bc194093957e.png)

- Once in the detail of a particular secret, do we need an "Edit" button? Should it not just be editable automatically?

- So, we took the bulk of the form out of the "create" dialog and put it in the detail of each Secret, correct? ex: annotations and service account dropdown?

**Comment by kimholmes** [comment]
User Experience flow is as follows:
For access tokens, when the user creates a Secret, they have a choice between two types of Secrets, one with Username/Password or one with Access Token.

**Username/Password:**
![accessTokens1](https://user-images.githubusercontent.com/21316329/64477871-76211c80-d16e-11e9-9a73-7ab60b387ea8.png)

**Access Token:**
![accessTokens2](https://user-images.githubusercontent.com/21316329/64477880-94871800-d16e-11e9-836e-ccceca2e0a2d.png)

**Comment by ncskier** [comment]
It seems like there are a number of secrets & options that we can configure in the Dashboard, but at the moment we would like to keep things as minimal as possible. So, I did some research to try and clarify what we want to show in the Secrets view:

Tekton supported Secret types are:
- `kubernetes.io/basic-auth`
- `kubernetes.io/ssh-auth`
- Access Tokens (`Opaque`) (https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource)

[And they also sort-of support](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#kubernetess-docker-registrys-secret):
- `kubernetes.io/dockercfg`
- `kubernetes.io/dockerconfigjson`

---
At the moment, it looks like we can cover all of our use cases by allowing users to manage the following secret types:
- `kubernetes.io/basic-auth`
- `kubernetes.io/ssh-auth`
- `Opaque`

These secrets will have the option of being patched to ServiceAccounts as regular secrets (not as ImagePullSecrets). For example, [this](https://github.com/pipeline-hotel/example-pipelines/blob/master/create-tekton-docker-secret.sh#L18) script to prepare secrets for the pipeline-hotel Pipeline.

We must be able to add Annotations to the `basic-auth` & `ssh-auth` secrets, but not to the `Opaque` secrets.

Since we don't want the Tekton Dashboard to become a Kubernetes Dashboard, I think that we should keep our Secret management limited to this for now. 

@mnuttall and/or @dibbles can you please validate that the scenario I've proposed above will cover all of our current use-cases with the webhook extension & tekton dashboard?

**Comment by ncskier** [comment]
I clarified with Mark, that we are not concerned with `kubernetes.io/ssh-auth` secrets for Access Token Management.

**Comment by mii-w** [comment]
<img width="1055" alt="Screen Shot 2019-09-20 at 11 47 52 AM" src="https://user-images.githubusercontent.com/51759906/65340555-7f61ae80-db9c-11e9-877b-9bbf9aaf72c2.png">

**Comment by mii-w** [comment]
![Screen Shot 2019-10-02 at 12 52 09 PM](https://user-images.githubusercontent.com/51759906/66064726-f7709280-e513-11e9-8ee8-35ecc584e9d3.png)
![Screen Shot 2019-10-02 at 12 55 45 PM](https://user-images.githubusercontent.com/51759906/66064765-0b1bf900-e514-11e9-8145-9eef3ee350b3.png)

![Screen Shot 2019-10-02 at 12 55 28 PM](https://user-images.githubusercontent.com/51759906/66064737-fb9cb000-e513-11e9-8ed4-f5cd96f72e86.png)
![Screen Shot 2019-10-02 at 12 55 34 PM](https://user-images.githubusercontent.com/51759906/66064740-fd667380-e513-11e9-8faa-73757a288287.png)
