### ISSUE TITLE
Tekton Triggers resources in different namespace from Tekton Pipelines

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#400]
# Expected Behavior
I expect to import my Tekton resources all into the Namespace that I am operating under. For example, if I want to run my Pipeline in Namespace `foo`, then I expect to import my Tekton Pipelines, Tasks, TriggerTemplates, TriggerBindings, etc. into the `foo` Namespace.

# Actual Behavior
Currently, for the webhooks extension to function properly, the Tekton Pipeline resources must be created in the `foo` Namespace, but the Tekton Triggers resources must be created in the `tekton-pipelines` namespace (or wherever I've installed the webhooks extension). As a user, this separation is strange since the Pipelines, TriggerTemplates, and TriggerBindings are tightly coupled. It would be very nice if I could import all of my Tekton resources together into the `foo` Namespace.

**Comment by dibbles** [comment]
The problem here is that we run a single eventlistener ..... to facilitate this, we would need to move an eventlistener per pipeline (which could be in multiple namespaces) - this then means a single repo might need to have multiple webhooks configured against it if it wants to run multiple pipelines...... it becomes a question of the architecture we want to run with.

OR ..... it is a question of whether the trigger codebase needs changing to facilitate and eventlistener in one namespace being able to use templates and bindings in another namespace. 

@mnuttall ..... this probably needs some discussion.

**Comment by ncskier** [comment]
Throwing out another idea, we could run one EventListener per Namespace. So the EventListener would have access to the resources in its Namespace.

**Comment by a-roberts** [comment]
> If we make a change in Triggers, then we will need to get it into Triggers v0.2.0, then use the new Triggers release in early January. The timing could be a little rough. So, I personally think it would be easier to update the webhooks extension.
> 
> Throwing out another idea, we could run one EventListener per Namespace. So the EventListener would have access to the resources in its Namespace. I think this could reuse most of the logic we already have for the webhooks extension.

Seems reasonable, so when creating a webhook we'd use the namespace there instead of the install namespace, see https://github.com/tektoncd/experimental/blob/master/webhooks-extension/pkg/endpoints/webhook.go#L444 for that EventListener, and the namespace itself does get included in the route, for example I've got this route:

```
el-tekton-webhooks-eventlistener   el-tekton-webhooks-eventlistener-tekton-pipelines.apps.myip.com             el-tekton-webhooks-eventlistener   <all>
```

And of course we'd have to do the same for the validator service and update our test code. Atm I'm preferring this approach instead of one EventListener per pipeline as it seems like less work.
