### ISSUE TITLE
Webhook 422 Validation Failed Error

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#405]
I tried creating a Webhook on OpenShift, and ran into this error after clicking the `Create` button:
```
{"level":"debug","msg":"Webhook SSL verification: false"}
{"level":"debug","msg":"Deleting triggers for go-hello-world-webhook-demo from the eventlistener"}
{"level":"debug","msg":"route deletion succeeded"}
{"level":"error","msg":"Error for RespondError: POST https://github.ibm.com/api/v3/repos/bcwalker/go-hello-world/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:The URL you've entered is not valid. Please make sure that you encode all special characters first}]."}
{"level":"error","msg":"Response is {0xc0005aec40 application/json [application/json application/json] 200 0 true <nil> 0xc0005aec40}."}
```

Here's a screenshot:
![Screen Shot 2019-12-12 at 2 18 35 PM](https://user-images.githubusercontent.com/16961496/70741904-66275480-1cea-11ea-9192-bb1b267226ed.png)

I've successfully created the same webhook with these credentials on Docker for Desktop, so I'm not sure what's going wrong.

I also tried with a public GitHub url, and it also failed:
![Screen Shot 2019-12-12 at 2 57 54 PM](https://user-images.githubusercontent.com/16961496/70744528-db495880-1cef-11ea-9a00-c1ebdbc9c56c.png)

## Installation versions
- Webhook Extension v0.3.0 release yaml from the Dashboard release: https://github.com/tektoncd/dashboard/releases/download/v0.3.0/openshift-tekton-webhooks-extension-release.yaml
- Dashboard v0.3.0
- Tekton Pipelines form the OpenShift Operator 0.8.1
- Tekton Triggers v0.1.0

**Comment by a-roberts** [comment]
This is an interesting one, I hit the encoding message error too. May be different to your circumstance but can you check your image in use for Tekton Pipelines, and that the ClusterRoleBinding is set up and being used correctly (e.g. by Tekton Pipelines in the openshift-pipelines namespace)? 

IIRC I was actually using 0.7 and it was to do with serviceAccountName and we were surfacing such an error instead.

Also I noticed `default` as your ServiceAccount in the table instead of a sufficiently augmented one like `tekton-webhooks-extension`.

**Comment by ncskier** [comment]
Following up on this issue, it was user error. I did not change the `WEBHOOK_CALLBACK_URL` in the `webhooks-extension` deployment (install instructions [here](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/InstallNightlyBuild.md)).

However, I think that this is a gap in the Webhook Extension's UX, so I've created a UX issue here: https://github.com/tektoncd/experimental/issues/414
