### ISSUE TITLE
Add Triggers 0.5 support for webhooks extension

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/experimental#547]
# Expected Behavior
I should be able to install master of the webhooks-extension when using Triggers 0.5 on Openshift

# Actual Behavior
The webhooks-extension won't install, with this error:
```
Error from server (BadRequest): error when creating "STDIN": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "type"
2020/05/21 11:09:53 error executing 'kubectl apply': exit status 1
```

# Steps to Reproduce the Problem

1. Set up an openshift cluster with Triggers 0.5 (and any version of the dasboard)
2. Try to install webhooks
3. Notice failure

# Additional Info

**Comment by booninite** [comment]
Unsure if this is related to using Triggers 0.5, but I am also seeing that the resources are always scheduled in the extensions installation namespace instead of the target namespace.

**Comment by a-roberts** [comment]
I'll look into this, like Megan I see this on Docker Desktop as well actually

The resources mentioned from the error:

```
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
```

```
Resource: "triggers.tekton.dev/v1alpha1, Resource=triggertemplates", GroupVersionKind: "triggers.tekton.dev/v1alpha1, Kind=TriggerTemplate"
Name: "monitor-task-template", Namespace: "tekton-pipelines"
```

```
for: "STDIN": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "type"
```

**Comment by a-roberts** [comment]
https://github.com/tektoncd/triggers/issues/583 here's the issue I see, so I can code around it by removing the type: specifiers and deleting existing TriggerTemplates, and add it to our readme, but wondering if Triggers want to do anything as well so users don't need to.

I'll go about testing what I've got now to check nothing breaks.

**Comment by a-roberts** [comment]
I've made a PR but let's not merge it yet until we hear back from the Triggers folks.

Hey @booninite, regarding resources always being scheduled in the extensions installation namespace instead of the target namespace: I created a webhook on Docker Desktop with the extension installed in `tekton-pipelines` but the target namespace being `default`

![image](https://user-images.githubusercontent.com/12814972/82888046-c2043380-9f40-11ea-822b-32c92cd67cee.png)

![image](https://user-images.githubusercontent.com/12814972/82888071-c892ab00-9f40-11ea-9bc3-d0c2062badc1.png)
