### ISSUE TITLE
Tekton Hub Task display name capitalization

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/experimental#581]
![tekton-hub-uniform-capitalization](https://user-images.githubusercontent.com/3650655/86787929-3c1cf180-c083-11ea-8e70-817382227b9d.png)

How is the Display name capitalization decided. 

# Actual Behavior

Task Display name capitalization looks inconsistent. 
Is this by design

# Expected Behavior

Consistent Display name capitalization

# Steps to Reproduce the Problem

https://ui-tekton-hub.apps.openshift-web.p0s5.p1.openshiftapps.com/

**Comment by sthaha** [comment]
@nikhil-thomas This is by design. The task/resource has an annotation that can be used to set a display name. 
Hub will render the `annotation.displayName:` as is (i.e. no modifications/formatting applied), so it is under users control (e.g. `OpenShift` vs `Openshift` vs `openshift` ) how they want the name to be displayed. 

In the absence of a displayName, hub displays the `metadata.name` as is.
