### ISSUE TITLE
Webhooks - credential POST should not take namespace as query parameter

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#69]
When creating a credential using the webhooks extension the API uses:
```
POST /webhooks/credentials?namespace=x
{
  "name": "my-access-token",
  "accesstoken": "ksdufbliubsliuvbsliucbsiucslicbsh98wehr8w9huwbcwb87ec"
}
```
This is inconsistent with create webhook and general practice, where the namespace would be included in the body of the post, not as a query parameter.

**Comment by vtereso** [comment]
The dashboard credential is our visualization of a secret although it has a secret backing. In this way, we get the worst of both worlds since we cannot directly use credentials as CRD or use information such as namespace that is naturally available, etc. The experimental repo does the same, but exposes a different view of the secrets that back it. Likely, we should swap to using secrets in the dashboard and extensions may access that endpoint.

**Comment by a-roberts** [comment]
@vtereso I agree, we should cover that as a new issue (I believe we discussed this on a scrum, it would be useful to do a "spike' where we figure out why we have what we have now for credentials and go from there).

As part of this task I'll do what it says on the tin and make it a path parameter, updating tests etc and docs.

**Comment by a-roberts** [comment]
Merged so closing
